-- Migration 0025: workflow_identity_successor_lines
--
-- PURPOSE:
-- IMMUTABLE successor/lineage surface for P9 historical identity repair
-- (SVC_WORKFLOW_CANONICAL_IDENTITY_RECONCILIATION_V2, CTR-CIR-001/004/006/007
-- read-projection delta): map STALE auth naked-name Principals to their unique
-- canonical successors so that current resolution paths uniquely yield the
-- canonical Agent WITHOUT rewriting history.
--
-- IMMUTABILITY BOUNDARY (hard):
--   - No UPDATE/DELETE of workflow_node_visits, workflow_events, or any
--     historical fact is authorized by this migration. This table is purely
--     ADDITIVE: one append-only line per stale source Principal.
--   - It is a repair-lineage read surface, NOT a fake equivalence record
--     between old and new Principals: the stale Principal keeps its own
--     history and gains no alias authority; reads may enrich the projected
--     assignee identity with the canonical agent id recorded here.
--   - The table itself is append-only: a BEFORE UPDATE/DELETE trigger raises
--     for every mutation attempt (rows are written exactly once by the
--     offline identity_repair_v1 operator).
--
-- Columns:
--   id                      uuid PK, generated by the database.
--   source_principal_id     stale (naked-name) Workflow Principal. UNIQUE:
--                           exactly ONE successor per source — this makes
--                           many-to-one ambiguity impossible at the DB level.
--   successor_principal_id  canonical successor Workflow Principal (AGENT).
--   legacy_agent_id         auth-side naked agentId of the source, e.g.
--                           'writing-style-analyst-agent'.
--   canonical_agent_id      canonical agentId, e.g.
--                           'agt_writing-style-analyst-agent'.
--   classification          closed set:
--     'STALE_PRINCIPAL_WITH_UNIQUE_REPAIR'  - P9 naked-name repair pair
--     'MECHANICALLY_PROVEN_SUCCESSOR'       - successor proven mechanically
--   evidence                jsonb blob recorded as given by the census phase
--                           (directory cross-check is performed there, not by
--                           the operator).
--   repair_reason           human-readable reason, written by the operator.
--
-- NOTE: EXPECTED_MIGRATION_VERSION must be updated from 24 to 25 in
-- src/http/mod.rs for /readyz to return "ready".

CREATE TABLE workflow_identity_successor_lines (
    id                      UUID        NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
    source_principal_id     UUID        NOT NULL,
    successor_principal_id  UUID        NOT NULL,
    legacy_agent_id         TEXT        NOT NULL,
    canonical_agent_id      TEXT        NOT NULL,
    classification          TEXT        NOT NULL CHECK (classification IN (
                                'STALE_PRINCIPAL_WITH_UNIQUE_REPAIR',
                                'MECHANICALLY_PROVEN_SUCCESSOR')),
    evidence                JSONB       NOT NULL,
    repair_reason           TEXT        NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- One successor per source principal: prevents many-to-one ambiguity
    -- at the database level (no source can gain a second lineage line).
    UNIQUE (source_principal_id)
);

-- Successor-side lookups: ambiguity detection (is this successor Principal
-- already claimed with a different canonical agent id?) and read projections.
CREATE INDEX idx_wisl_successor_principal
    ON workflow_identity_successor_lines (successor_principal_id);

-- Append-only enforcement: the lineage surface is IMMUTABLE once written.
CREATE OR REPLACE FUNCTION fn_wisl_append_only()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION
        'wisl_append_only: cannot % workflow_identity_successor_lines; the successor lineage surface is append-only',
        TG_OP
        USING ERRCODE = '23000';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_wisl_append_only
    BEFORE UPDATE OR DELETE ON workflow_identity_successor_lines
    FOR EACH ROW EXECUTE FUNCTION fn_wisl_append_only();
